// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDezZPy_ZPZdor-Mi7GxEBwbdRDLmg0r8Y',
    appId: '1:617517085846:web:827aeadbc077569188feb7',
    messagingSenderId: '617517085846',
    projectId: 'kabutaar-fd1d0',
    authDomain: 'kabutaar-fd1d0.firebaseapp.com',
    storageBucket: 'kabutaar-fd1d0.appspot.com',
    measurementId: 'G-VVLXJ0KYD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl7ZNnYlRjgC3QzjsED0mUaYVd2X6R9eY',
    appId: '1:617517085846:android:e9637d3d7e4c8c0088feb7',
    messagingSenderId: '617517085846',
    projectId: 'kabutaar-fd1d0',
    storageBucket: 'kabutaar-fd1d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfOtiYYJ6ffoPTPy9P4rwQ4MdRG92Vck',
    appId: '1:617517085846:ios:14d73edecb9ad33088feb7',
    messagingSenderId: '617517085846',
    projectId: 'kabutaar-fd1d0',
    storageBucket: 'kabutaar-fd1d0.appspot.com',
    iosClientId: '617517085846-b4hil5vcqcvcrln5129f9tfkticujaii.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutterProject',
  );
}
